# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\"\x1e\n\x0eSuggestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"D\n\x0fSuggestResponse\x12\x17\n\x0f\x66irstSuggestion\x18\x01 \x03(\t\x12\x18\n\x10secondSuggestion\x18\x02 \x03(\t2^\n\x0eSuggestService\x12L\n\x0f\x46indSuggestions\x12\x1b.suggestions.SuggestRequest\x1a\x1c.suggestions.SuggestResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTREQUEST']._serialized_start=34
  _globals['_SUGGESTREQUEST']._serialized_end=64
  _globals['_SUGGESTRESPONSE']._serialized_start=66
  _globals['_SUGGESTRESPONSE']._serialized_end=134
  _globals['_SUGGESTSERVICE']._serialized_start=136
  _globals['_SUGGESTSERVICE']._serialized_end=230
# @@protoc_insertion_point(module_scope)
