# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: suggestions.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11suggestions.proto\x12\x0bsuggestions\x1a\x1bgoogle/protobuf/empty.proto\"\x1e\n\x0eSuggestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"D\n\x0fSuggestResponse\x12\x17\n\x0f\x66irstSuggestion\x18\x01 \x03(\t\x12\x18\n\x10secondSuggestion\x18\x02 \x03(\t\"(\n\x10\x43learDataRequest\x12\x14\n\x0cvector_clock\x18\x01 \x03(\x05\x32^\n\x0eSuggestService\x12L\n\x0f\x46indSuggestions\x12\x1b.suggestions.SuggestRequest\x1a\x1c.suggestions.SuggestResponse2S\n\x0bYourService\x12\x44\n\tClearData\x12\x1d.suggestions.ClearDataRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'suggestions_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUGGESTREQUEST']._serialized_start=63
  _globals['_SUGGESTREQUEST']._serialized_end=93
  _globals['_SUGGESTRESPONSE']._serialized_start=95
  _globals['_SUGGESTRESPONSE']._serialized_end=163
  _globals['_CLEARDATAREQUEST']._serialized_start=165
  _globals['_CLEARDATAREQUEST']._serialized_end=205
  _globals['_SUGGESTSERVICE']._serialized_start=207
  _globals['_SUGGESTSERVICE']._serialized_end=301
  _globals['_YOURSERVICE']._serialized_start=303
  _globals['_YOURSERVICE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
