# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x0btransaction\x1a\x1bgoogle/protobuf/empty.proto\"h\n\x13VerificationRequest\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x0b\n\x03zip\x18\x05 \x01(\t\"B\n\tOrderItem\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\":\n\x08UserData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\"(\n\x14VerificationResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\"(\n\x10\x43learDataRequest\x12\x14\n\x0cvector_clock\x18\x01 \x03(\x05\x32n\n\x12TransactionService\x12X\n\x11VerifyTransaction\x12 .transaction.VerificationRequest\x1a!.transaction.VerificationResponse2S\n\x0bYourService\x12\x44\n\tClearData\x12\x1d.transaction.ClearDataRequest\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VERIFICATIONREQUEST']._serialized_start=76
  _globals['_VERIFICATIONREQUEST']._serialized_end=180
  _globals['_ORDERITEM']._serialized_start=182
  _globals['_ORDERITEM']._serialized_end=248
  _globals['_USERDATA']._serialized_start=250
  _globals['_USERDATA']._serialized_end=308
  _globals['_VERIFICATIONRESPONSE']._serialized_start=310
  _globals['_VERIFICATIONRESPONSE']._serialized_end=350
  _globals['_CLEARDATAREQUEST']._serialized_start=352
  _globals['_CLEARDATAREQUEST']._serialized_end=392
  _globals['_TRANSACTIONSERVICE']._serialized_start=394
  _globals['_TRANSACTIONSERVICE']._serialized_end=504
  _globals['_YOURSERVICE']._serialized_start=506
  _globals['_YOURSERVICE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
