# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x08\x65xecutor\"!\n\x0e\x45xecuteRequest\x12\x0f\n\x07orderId\x18\x01 \x01(\t\"#\n\x0f\x45xecuteResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x32U\n\x13\x45xecuteOrderService\x12>\n\x07\x45xecute\x12\x18.executor.ExecuteRequest\x1a\x19.executor.ExecuteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EXECUTEREQUEST']._serialized_start=28
  _globals['_EXECUTEREQUEST']._serialized_end=61
  _globals['_EXECUTERESPONSE']._serialized_start=63
  _globals['_EXECUTERESPONSE']._serialized_end=98
  _globals['_EXECUTEORDERSERVICE']._serialized_start=100
  _globals['_EXECUTEORDERSERVICE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
